In [1]:
import numpy as np

# Fibonacci sequence

This loop prints the Fibonacci sequence until the $n$ element. For example the first 50 Fibonacci sequence numbers

In [6]:
n=50

f_0 = 0
f_1 = 1
Fibonacci = [f_0, f_1]

for i in range(2, n):
    f_n = f_0 + f_1
    f_0 = f_1 + 0
    f_1 = f_n + 0
    Fibonacci.append( f_n )
    
print("Fibonacci sequence:", Fibonacci)

Fibonacci sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049]


# Factorial of a number !

For a integer number $n \in N$, the factorial of $n$ is (n)! equal to the product of all the integer numbers less and equal of $n$:

$$ n! = (n)(n-1)(n-2)\dots (2)(1) $$

This function returns the array of all the subproducts of $n$ since $0! = 1, 1! = 1$ until $n!$ for purposes of reusing the subproducts in simplification

In [12]:
def factorial(n):
    result = 1
    factorials = []
    for i in range(n):
        result *= (i+1)
        factorials.append(result)
    return factorials

In [13]:
factorial(5)

[1, 2, 6, 24, 120]

# Prime factorization

Every integer number can be writen as the product of powers of prime numbers. And this prime factorizartion is unique

For an integer number $n$:

$$ n = p_1^{k_1} p_2^{k_2} \dots p_m^{k_m} $$

for $p_1, p_2 \dots p_m$ prime numbers and $k_1, k_2 \dots k_m$ a unique set of integers for $n$.

This function returns the prime decomposition of an integer as an array of pairs $(p_i, k_i)$.

In [113]:

def factorize(number):
    factors = []
    for i in range(2, number + 1 ):
        if not(number % (i) ):
            isAPrime = True
            for j in factors:
                if not((i) % j[0]):
                    isAPrime = False
            if isAPrime:
                exponent = 0
                while( not (number % (i**exponent)) ):
                    exponent += 1
                
                factors.append( [i, exponent-1] )
    return np.array(factors)

In [127]:
factorization = factorize(120)
factorization

array([[2, 3],
       [3, 1],
       [5, 1]])

# Factors of a number

The factor of a integer $n$ are all the (less) integers that can divide $n$. And given a prime factorization it can be calculated the total amount of factors of a number by:

$$ (k_1 + 1)(k_2 + 1) \dots (k_m + 1) $$

In [337]:
def number_of_factors(n):
    factorization = factorize(n)
    print("Prime factorization:\n", factorization)
    n_factors = 1
    for j in (factorization[:,1] + 1):
        n_factors *= j
    n_factors
    return n_factors

In [338]:
number_of_factors(30)

Prime factorization:
 [[2 1]
 [3 1]
 [5 1]]


8

In [132]:
import itertools 

In [335]:
def multiplyElements(array, factors_temp, factors_current):
    
    temp_array = []
    for i in factors_temp:
        for j in factors_current:
            mult = i*j
            temp_array.append(mult)

    concat = np.concatenate([ factors_current, temp_array ])
    
    if len(array) > 0:
        return multiplyElements(array[1:], array[0], concat)
    else:
        return concat
    
def findFactors(n):
    factorization = factorize(n)
    group_factors = []
    for prime, power in factorization:
        subgroup_factors = []
        for exp in range(1, power+1):
            subgroup_factors.append(prime**exp)
        group_factors.append(subgroup_factors)
    
    return multiplyElements(group_factors[1:], group_factors[0], [1])

In [336]:
findFactors(104400)

array([     1,      2,      4,      8,     16,      3,      6,     12,
           24,     48,      9,     18,     36,     72,    144,      5,
           10,     20,     40,     80,     15,     30,     60,    120,
          240,     45,     90,    180,    360,    720,     25,     50,
          100,    200,    400,     75,    150,    300,    600,   1200,
          225,    450,    900,   1800,   3600,     29,     58,    116,
          232,    464,     87,    174,    348,    696,   1392,    261,
          522,   1044,   2088,   4176,    145,    290,    580,   1160,
         2320,    435,    870,   1740,   3480,   6960,   1305,   2610,
         5220,  10440,  20880,    725,   1450,   2900,   5800,  11600,
         2175,   4350,   8700,  17400,  34800,   6525,  13050,  26100,
        52200, 104400])

# Digital root

Every integer $m$ can be decomposed by the sum of its $n+1$ digits (times powers of 10):

$$ m = d_0(10^0) + d_1(10^1) + \dots d_{n-1}(10^{n-1}) + d_n(10^n) $$

The digital root of a number is the sum of all its $n+1$ digits.

In [103]:

def digitalDecomp(n):
    n_digits = int(np.log10(n)) + 1
    decomp = []
    for i in range(n_digits):
        digit = n - (n//10)*10
        decomp.append([10**i, digit])
        n = int(n / 10)
    return np.array(decomp)

In [107]:
decomp = digitalDecomp(37173)
print(decomp)

[[    1     3]
 [   10     7]
 [  100     1]
 [ 1000     7]
 [10000     3]]


In [105]:
def digitalRoot(number):
    decomp = digitalDecomp(number)
    digitalSum = sum(decomp[:,1])
    if digitalSum > 9:
        return digitalRoot(digitalSum)
    else:
        return digitalSum

In [109]:
digitalR = digitalRoot(1)
print(digitalR)

1
